payment:
  success-rate: 0.7

server:
  port: 8084
spring:
  application:
    name: payment-service
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-discovery:8001/eureka

