
server:
  port: 8008

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-discovery:8001/eureka


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service
  rabbitmq:
   username: guest
   port: 5672
   password: guest
   host: localhost